########################################################
### redis
########################################################
spring:
  redis:
    database: 0
    host: 127.0.0.1
    ssl: false
    port: 6379
    timeout: 100000


